[package]
name = "atsdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.11.2"
datafusion = "5.0.0"
snafu = "0.7.0-beta.1"
tokio = "1.11.0"
